- templates/docker/Dockerfile_centos7.template
- Split gcc7 build to separate stage
- Copy Dockerfile to root of the container
- Generic improvements to make recipe better and align with latest
ubuntu recipe
> Improve centos7 docker recipe

- generatedDockerfiles/ngc/Makefile
Verified locally by running 
$ make
&
$ make clean
> Fix minor inconsistencies in NGC makefile

- commands/buildDockerImage.sh
- supportfiles/.condarc
- supportfiles/.condarc-cuda10.0
- supportfiles/.condarc-cuda9.2
edit. gpuci dockerfile seems to have been removed. No problem anymore with it.
> Remove cuda labels from .condarc

- doc/Dockerhub_rapidsai-dev-nightly.md
- doc/Dockerhub_rapidsai-dev.md
- doc/Dockerhub_rapidsai-nightly.md
- doc/Dockerhub_rapidsai.md
- doc/NGC_rapidsai.md
Initial version of revised READMEs for DockerHub and NGC
> Initial version of revised READMEs for DockerHub and NGC

- generatedDockerfiles/Dockerfile.centos7-base
- generatedDockerfiles/Dockerfile.centos7-devel
- generatedDockerfiles/Dockerfile.centos7-runtime
- generatedDockerfiles/Dockerfile.ubuntu-base
- generatedDockerfiles/Dockerfile.ubuntu-devel
- generatedDockerfiles/Dockerfile.ubuntu-runtime
- templates/docker/conda_install_notebookenv
Adding cuxfilter to runtime images.
> [ENH] Adding cuxfilter to runtime images

- supportfiles/test.sh
- templates/docker/build_rapids
Merge when runtime builds with new notebooks repo are green.
The `-l` addition to the cudf build script is for newly added optional legacy tests.
> [WIP] Update notebook testing and cudf legacy test build option

- README.md
- Add missing links to stable/night as well as links to the tags for types
- Give a more context and detail around extending images
- Rearrange docs links
> DOC Add some clarification to the README

- supportfiles/test.sh
Updated test.sh to accommodate new notebook repo layout.
These changes were taken from a local copy that was modified and tested in a recent nightly devel container, and comments were added.
> [BUG] Updated test.sh to accommodate new notebook repo layout

- supportfiles/test.sh
I had previously put in the wrong filename in #79. This fixes that.
> fix cuml-benchmarks notebook exception

- .github/workflows/dockerfiles.yaml
This PR adds a GitHub action to automatically generate the latest Dockerfiles anytime a PR is merged to the repo's default branch.
> Add GitHub Action for Generating Dockerfiles

- .github/workflows/dockerfiles.yaml
This PR fixes the variable interpolation for our GitHub action.
> Fix GitHub Action env variable interpolation

- templates/Devel.dockerfile.j2
This PR is a continuation of https://github.com/rapidsai/build/pull/87. GitHub was having issues and for some reason my comment was committed.
> add gsfonts comment

- CONTRIBUTING.md
This PR updates some of the verbiage in `contributing.md`.
> Docs update

- CONTRIBUTING.md
This PR fixes the `README.md` link in `CONTRIBUTING.md`
> Fix docs link

- templates/partials/devel_build.dockerfile.j2
I broke the cudf build step in https://github.com/rapidsai/build/pull/101. This fixes it.
> Fix cudf build step

- context/.start_jupyter_run_in_rapids.sh
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
Closes https://github.com/rapidsai/docker/issues/120
Added output that notebooks server has been started and how it can be reached.
> [REVIEW] Add Notebook Server Instructions

- context/.start_jupyter_run_in_rapids.sh
Closes #120
Added output of what ports need to be exposed when running the runtime/devel container.
> [REVIEW] Add Notebook Ports Instructions

- context/.start_jupyter_run_in_rapids.sh
Closes #96 
Simple instruction added during runtime container execution.
> [REVIEW] Add Container Entrypoint Info

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
Adding ucx-py to builds as they were also removed from meta environment.
> [REVIEW] Add ucx-py to devel builds

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-quick.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-quick.Dockerfile
- settings.yaml
- templates/partials/devel_build.dockerfile.j2
This PR makes three changes:
1) Slightly changes build for CUDA 11 for c++14
2) Changes xgboost repo URL & branch
3) Enables xgboost rmm plugin
> Changes to xgboost build process

- ci/axis/base-runtime.yaml
- ci/axis/devel.yaml
This PR updates the axis files in `branch-0.15` for the `0.15` release.
> [REL] Update branch-0.15 for 0.15 release

- LICENSE
This PR adds a license to the repo. Closes #159
> Add LICENSE to repo

- dockerhub-readme/Dockerhub_rapidsai-dev-nightly.md
This PR updates some versions in the DockerHub readmes.
> Update dockerhub readmes

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
Merge the build process into one line. Tests can't be on a line by itself since all it does is set a cmake parameter.
> [REVIEW] FIX Build tests in devel images

- blazing-dev/ci/axis/devel.yaml
- ci/axis/base-runtime.yaml
- ci/axis/devel.yaml
This PR updates the axes for `0.16` release.
> Update axes for 0.16 release.

- dockerhub-readme/Dockerhub_blazing-dev-nightly.md
- dockerhub-readme/Dockerhub_blazing-dev.md
- dockerhub-readme/Dockerhub_rapidsai-dev-nightly.md
- dockerhub-readme/Dockerhub_rapidsai-dev.md
- dockerhub-readme/Dockerhub_rapidsai-nightly.md
- dockerhub-readme/Dockerhub_rapidsai.md
- dockerhub-readme/NGC_rapidsai.md
This PR updates the DockerHub READMEs for release 0.16.
Closes #174
> DockerHub README Updates for Release 0.16

- blazing-dev/ci/axis/devel.yaml
- generated-dockerfiles/centos7-base.Dockerfile
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-base.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Base.dockerfile.j2
- templates/Devel.dockerfile.j2
- templates/Runtime.dockerfile.j2
- templates/partials/patch.dockerfile.j2
With the merge of #199 this will update `main` and release `v0.16.0`
> [RELEASE] v0.16 updated release

- generated-dockerfiles/centos7-base.Dockerfile
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-base.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/partials/patch.dockerfile.j2
This PR updates the `npm` patch to resolve vulnerabilities in the container.
> Update npm patch

- generated-dockerfiles/centos7-base.Dockerfile
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-base.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/partials/patch.dockerfile.j2
This PR updates the `npm` patch to resolve vulnerabilities in the container.
> Update npm patch (branch-0.17)

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
This PR builds the tests in `cuml` and `cuspatial` in level images.
> #1254: Make sure all repos are building tests in devel images

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/partials/install_notebooks.dockerfile.j2
> Install ipywidgets Jupyter Lab extension

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
This PR updates the build command for cugraph based on their recent PR https://github.com/rapidsai/cugraph/pull/1267.
> Update cugraph build command

- .github/workflows/dockerhub-readme.yml
This PR adds DockerHub readme autogeneration via a GH Action.
https://github.com/rapidsai/docker/pull/225/checks?check_run_id=1512216313
> add docker hub readme autogeneration action

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Remove 0.18 config from ci/axis files now that code freeze has hit and we're on separate branches prior to release
> FIX Remove 0.18 testing for branch-0.17

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Current axis files are still set for nightly repos, updating files for release
> FIX Correct exclusions for release 0.17

- generated-dockerfiles/rapidsai-clx_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-clx/Runtime.dockerfile.j2
- templates/rapidsai-clx/partials/clone_and_build_clx.dockerfile.j2
- Update to latest stable PyTorch (v1.7.1)
- Add SlashNext URL Analysis and Enrichment
> Update CLX dependencies

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
For 0.19 images before release
> [REVIEW] FIX Add 0.19 to axis

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR updates the axes files for the 0.18 release.
> Update 0.18 axes for release

- generated-dockerfiles/rapidsai_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai/Runtime.dockerfile.j2
This PR fixes the cudatoolkit version that's used for `rapidsai` images.
> Fix cudatoolkit version

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai-core/partials/patch.dockerfile.j2
Added logic to use yum for package patching in centos.
> [REVIEW] FIX Handle centos for CVE patching

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai-core/partials/patch.dockerfile.j2
This PR syncs the `main` branch with `branch-0.18`.
> [HOTFIX] Remove nightly channels from stable builds

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai-core/partials/patch.dockerfile.j2
This PR cherry-picks the following PRs from `branch-0.18` into `branch-0.19` to get them in sync:
- #280
- #283
- #285
- #287
> Sync 0.19 with 0.18 hotfixes

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR adds `RAPIDS_VER` `0.20` to all of our axes.
> Add 0.20 to axis

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
This fixes the current broken docker builds. Confirmed locally.
> [REVIEW] FIX Define compiler vars

- .github/workflows/generated-files.yml
- RELEASE.md
This PR adds some documentation about the release process for the `rapidsai/docker` repo.
> Add RELEASE.md doc

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Updating CI axis for release, excluding nightly 0.20 and building off release images
> [REVIEW] REL Update axis for release

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
- templates/rapidsai-core/partials/patch.dockerfile.j2
This PR merges the latest `branch-0.19` changes into `branch-0.20`
> Merge `branch-0.19` into `branch-0.20`

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/os_pkgs.dockerfile.j2
Adds OpenMPI to base & runtime images to allow for multi-node NGC.
> Add `openmpi`

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai_centos8-devel.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai/partials/clone_and_build_blazing.dockerfile.j2
As we updated to GCC9, we need to update the path in the Dockerfiles
> Fix gcc path

- ci/gpuci/run.sh
> support space in workspace

- ci/axis/rapidsai-core-devel.yaml
- ci/gpuci/run.sh
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
cc @raydouglass @pentschev @quasiben
> Use UCX-Py 0.20

- .github/workflows/dockerhub-readme-nightly.yml
This PR updates the GH Action that publishes the DockerHub READMEs to trigger on the new calver branches.
> Update dockerhub-readme-nightly.yml Action

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR updates the axis files in anticipation of the `21.08` release.
> Update axis for `21.08` release

- context/source_entrypoints/runtime_devel.sh
- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
This PR backports #356 to `branch-21.08`.
> [HOTFIX] Update `runtime`/`devel` entrypoint

- context/entrypoint.sh
> Entrypoint script should error if commands fail

- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
> remove old cuda version

- RELEASE.md
- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR includes the following changes:
- Updates the `FROM_IMAGE` in our axis files
- Updates the steps in `RELEASE.md` to be more explicit about the changes that need to be made at release time
> Update `FROM_IMAGE` in axis files

- generated-dockerfiles/rapidsai-clx_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-devel.amd64.Dockerfile
- templates/rapidsai-clx/Devel.dockerfile.j2
- Remove `transformers` since already installed on base image.
- Remove `pytorch` 1.7.1 conda install. Forgot to delete this after updating to pip install v1.10.
> Update CLX devel dockerfiles

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Depends on https://github.com/rapidsai/integration/pull/422
> Remove Python 3.7 and add Python 3.9

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR adds `22.04` builds to our axes.
> Add `22.04` to axes

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR prepares the axis files for the `22.02` release.
> Prepare axis files for `22.02` release

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
This PR updates the `raft` build command.
> Fix `raft` build commands

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
* Use mamba to install jupyterlab-nvdashboard
Signed-off-by: Jordan Jacobelli <jjacobelli@nvidia.com>
* update generated_dockerfiles
Co-authored-by: Jordan Jacobelli <jjacobelli@nvidia.com>
> [HOTFIX] Backport #437 to `branch-22.02` (#444)

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR adds `22.06` to our axes so that we can start releasing `22.06` images.
> Add `22.06` to axes

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
This PR backports the changes from #449 into `branch-22.02`.
> [Backport} Set the default PATH to include the RAPIDS conda env

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
This PR merges some `branch-22.02` hotfixes into `main`.
> [HOTFIX] `branch-22.02` hotfixes

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
Apologies I got a quote in the wrong place in #449
> Fix Path quote placement

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
This PR backports #452  to `branch-22.02`.
> [Backport] Fix bad quote placement

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
This PR merges the latest backports from `branch-22.02` into `main`.
> [HOTFIX] Fix bad quote placement

- context/source_entrypoints/runtime_devel.sh
- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
- templates/rapidsai-core/partials/os_pkgs.dockerfile.j2
This PR merges #474 into the `main` branch.
> [HOTFIX] Merge `apt` key fix

- dockerhub-readme/generate_readmes.py
- dockerhub-readme/generated-readmes/ngc-rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/ngc-rapidsai-clx.md
- dockerhub-readme/generated-readmes/ngc-rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/ngc-rapidsai-core.md
- dockerhub-readme/generated-readmes/ngc-rapidsai-dev.md
- dockerhub-readme/generated-readmes/ngc-rapidsai.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
Adds NGC readmes for each of the new images being added to NGC.
This PR is best reviewed by commit.
> Add new NGC readmes

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- dockerhub-readme/generated-readmes/ngc-rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/ngc-rapidsai-clx.md
- dockerhub-readme/generated-readmes/ngc-rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/ngc-rapidsai-core.md
- dockerhub-readme/generated-readmes/ngc-rapidsai-dev.md
- dockerhub-readme/generated-readmes/ngc-rapidsai.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
Remove all references to CUDA 11.0
This PR is best reviewed by commit.
> Remove cuda 11.0

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR updates the axis for the `22.10` release.
> Update axis for `22.10` release

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Just adds `23.02` to all the axes.
> Add 23.02 to axes

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This updates the yaml axis entries for the 22.12 release
> Update dockerfile axis

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
This pin prevents a forced transitive dependency upgrade (Open SSL).
> Pin pyarrow to 9.0.0

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Depends on https://github.com/rapidsai/gpuci-build-environment/pull/282
> Add 23.04 to axes

- .github/workflows/generated-files.yml
- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Updates the CI axis files for the 23.02 release.
> Update ci axis

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Updates the axes for the v23.06 release
> Update axes for v23.06 release

- .github/ops-bot.yaml
Add the Branch Checker and Auto Merger to this repo.
> Enable ops-bot features

- .github/workflows/build-test-publish-images.yml
- .github/workflows/test-notebooks.yml
- Dockerfile
- ci/compute-matrix.jq
- matrix-test.yaml
- matrix.yaml
Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.08 to branch-23.10

- .github/workflows/build-test-publish-images.yml
- .github/workflows/update-dask-sql.yml
- Dockerfile
PR updates `rapidsai/ci` references to `rapidsai/ci-conda`
> Update image names

- raft-ann-bench/gpu/Dockerfile
The change in this PR was missed in #592 and should have been part of it.
> use rapidsai/miniforge instead of rapidsai/mambaforge

- Dockerfile
- raft-ann-bench/cpu/Dockerfile
- raft-ann-bench/gpu/Dockerfile
PR modifies dockerfiles to switch to using heredocs, getting rid of the `&&` and `\` characters in multi-line commands.
> Switch to heredocs

- Dockerfile
- context/notebooks.sh
- context/test_notebooks.py
Certain cugraph notebooks are excluded from testing as is implemented [here](https://github.com/rapidsai/cugraph/issues/2622). This PR updates this repository to reflect that requirement.
> fix cugraph notebooks

- context/raft-ann-bench/get_datasets.sh
- context/raft-ann-bench/run_benchmark.sh
- context/raft-ann-bench/run_benchmarks_preloaded_datasets.sh
Depends on https://github.com/rapidsai/raft/pull/2333
> Change `raft-ann-bench` package name to `raft_ann_bench`

- ci/compute-matrix.jq
Part of https://github.com/rapidsai/build-planning/issues/74.
> Add support for Ubuntu 24.04.

- ci/release/update-version.sh
Fix `update-version.sh` to also update `.yaml` workflow files
Skipping CI since this script is not tested in CI
> Fix update version

- .github/copy-pr-bot.yaml
- .github/ops-bot.yaml
- .github/workflows/release-to-nvstaging.yml
- context/cuvs-bench/get_datasets.sh
- context/cuvs-bench/run_benchmark.sh
- context/cuvs-bench/run_benchmarks_preloaded_datasets.sh
- cuvs-bench/README.md
- dockerhub-readme.md
- matrix-test.yaml
- matrix.yaml
- tests/container-canary/README.md
Fixes forward merger xref #756
> Forward-merge branch-25.06 into branch-25.08

- ci/compute-matrix.jq
- context/entrypoint.sh
- cuvs-bench/README.md
- dockerhub-readme.md
- matrix-test.yaml
- matrix.yaml
- tests/container-canary/README.md
Updates CUDA 12.8 to CUDA 12.9
Drops CUDA 11
> Update CUDA to 12.9, drop CUDA 11

- Dockerfile
- cuvs-bench/gpu/Dockerfile
- matrix.yaml
Just updates to use latest CUDA 12.9.1
> Update to CUDA 12.9.1

- .pre-commit-config.yaml
- README.md
- ci/create-cuvs-multiarch-manifest.sh
- ci/create-rapids-multiarch-manifest.sh
- dockerhub-readme.md
- matrix-test.yaml
Manual forward merge from 25.10 to 25.12. This PR should not be squashed.
Closes #791.
> Forward-merge branch-25.10 into branch-25.12
