- doc/Dockerhub_rapidsai-dev-nightly.md
- doc/Dockerhub_rapidsai-dev.md
- doc/Dockerhub_rapidsai-nightly.md
- doc/Dockerhub_rapidsai.md
This PR updates the build docs for the `0.12` release. The existing `readme.md`s were copied from the `rapidsai` org @ https://hub.docker.com/repositories and the `Current Version` and `Former Version` sections were all updated to include `0.12` and `0.11` respectively.
**Note:**
The docs include the mention of `cuxfilter` which hasn't yet been added to the container builds. I'll open a separate PR to add `cuxfilter` before this is merged.
> Update Docs for 0.12 Release

- doc/Dockerhub_rapidsai-dev-nightly.md
- doc/Dockerhub_rapidsai-dev.md
- doc/Dockerhub_rapidsai-nightly.md
- doc/Dockerhub_rapidsai.md
- doc/NGC_rapidsai.md
Due to it's dependencies it is not in the `base` or `devel` container
> Note cuxfilter is only in runtime containers

- templates/docker/Dockerfile_centos7-runtime.template
- templates/docker/Dockerfile_ubuntu-runtime.template
This PR updates the `base` image repo for our runtime images. Since the latest RAPIDS `base` images now get pushed to staging first, the `runtime` images must pull from the staging repo instead of the prod repo in order to get the latest `base` image.
Here's a quick screenshot of the images correctly pulling from the staging repo after these changes were made.
> Update Runtime base images

- templates/docker/Dockerfile_centos7-quick.template
- templates/docker/Dockerfile_ubuntu-quick.template
This PR updates the permissions in `/opt/conda` for `quick` builds. This is needed since the `quick` builds perform conda operations which modifiy the permissions in `/opt/conda` subdirectories.
> Update permissions on quick template

- templates/docker/gcc7_centos7
- templates/docker/gcc7_ubuntu
This fixes a problem for Ubuntu 18.04 where gcc was being updated to 7.5 from the `nvidia/cuda` version of 7.4. With 7.5 there are conflicts with GDAL and CUDA in cuspatial. Instead of updating our version of gcc in Ubuntu we are now relying on the version installed by `nvidia-cuda` containers
> Fix gcc 7 update issues

- README.md
- add-repo.md
- common-build-problems.md
- tooling.md
This PR separates the sections of the `readme.md` file into separate files for readability. Additionally a table was added to describe the 3 image types.
> Organize readme into separate files

- templates/docker/Dockerfile_centos7-quick.template
- templates/docker/Dockerfile_centos7-runtime.template
- templates/docker/Dockerfile_ubuntu-quick.template
- templates/docker/Dockerfile_ubuntu-runtime.template
This PR updates the staging repo used by our Docker images. We chose to separate our staging repos into a different DockerHub organization so that they didn't confuse end-users. Additionally, using private repos in our production DockerHub organization didn't work well with the [remote-docker-plugin](https://github.com/gpuopenanalytics/remote-docker-plugin).
Link to new DockerHub staging repo: https://hub.docker.com/u/rapidsaistaging
> Use New Staging Repo

- supportfiles/test.sh
This PR adds `cuml_benchmarks-test.py` to the exceptions list for notebook testing since it was causing the Jenkins job below to timeout. The `cuml` team suggested disabling it for Docker testing in the Slack thread below.
**References:**
[Jenkins job](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/nightly-tests/job/docker-test-notebooks/218/CUDA_VERSION=10.2,LINUX_VERSION=ubuntu18.04,PYTHON_VERSION=3.6/console)
[Slack thread](https://nvidia.slack.com/archives/CAL736F5W/p1589471616152100)
> Add cuml_benchmarks exception to notebook tests

- .gitignore
This PR removes an unnecessary `.gitignore` entry that is conflicting with a GitHub Action.
> Remove extraneous .gitignore entry

- .github/workflows/dockerfiles.yaml
This PR catches the `git commit` error that appears in our GitHub Action when there are no changes to commit.
> Catch GH Action Error

- templates/Devel.dockerfile.j2
This PR adds `gsfonts` to our ubuntu-devel images. `gsfonts` is necessary to correctly render diagram fonts in RAPIDS libraries' documentation.
> Add gsfonts to ubuntu-devel

- templates/Quick.dockerfile.j2
- templates/partials/devel_build.dockerfile.j2
In our pre-Jinja devel Dockerfiles, there was a [`chmod` step at the bottom of the file](https://github.com/rapidsai/build/blob/1fef16347ee58174c8a761aca322105f067023fe/generatedDockerfiles/Dockerfile.ubuntu-devel#L180) that was necessary to prevent file permission issues. 
The step was part of the Jupyter notebooks installation process which happened to (incorrectly) appear twice in the Dockerfile ([here](https://github.com/rapidsai/build/blob/1fef16347ee58174c8a761aca322105f067023fe/generatedDockerfiles/Dockerfile.ubuntu-devel#L174-L190) and [here](https://github.com/rapidsai/build/blob/1fef16347ee58174c8a761aca322105f067023fe/generatedDockerfiles/Dockerfile.ubuntu-devel#L92-L111)).
When I removed the duplicated notebook steps at the bottom of the devel files as part of the Jinja2 …
> Fix missing chmod in devel images

- settings.yaml
This PR updates the `xgboost` repo and tag used for `devel` images.
> Update xgboost repo/branch

- settings.yaml
This PR updates the `xgboost` repo and tag used for `devel` images.
> Update xgboost repo/branch in branch-0.15

- templates/partials/devel_build.dockerfile.j2
This PR removes the `build_tests_nvstrings` build step from our repo. It looks like it was removed from `cudf` in PR https://github.com/rapidsai/cudf/pull/5373 and is now causing issues in our builds.
> Remove nvstrings build step

- templates/Quick.dockerfile.j2
The `devel-quick` build [Jenkins job](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/docker/job/rapidsai-devel-quick-build/) has been failing over the past few days to due no `git` command found (see screenshot). This is likely due to the recent changes in parent images, but regardless we should probably use the conda environment here so that the version of `git` used in `quick` builds is the same as other builds.
> Use Conda Env for git for Quick Builds

- templates/Quick.dockerfile.j2
This PR fixes the `devel-quick` templates. It adds the missing `&&` that's necessary for multiple commands to be run in a single `RUN` step.
> devel-quick fix

- .github/workflows/dockerfiles.yaml
- .gitignore
- .pre-commit-config.yaml
- CONTRIBUTING.md
- generate_dockerfiles.py
This PR updates the workflow for the `docker` repo to reflect the following changes:
- The `generate_dockerfiles.py` script now writes Dockerfiles directly to `generated-dockerfiles/`.
- The existing GitHub action has been modified to validate that the files in `generated-dockerfiles/` are up-to-date before a PR can be merged. This means users will be responsible for running this whenever changes are introduced.
- A `.pre-commit-config.yaml` file has been introduced so that devs can opt-in to using [pre-commit](https://pre-commit.com/) hooks to automatically generate the latest Dockerfiles during commits.
The result of these changes is that reviewers will now be able to see how changes in the `templates/` directory affect the final Dockerfiles in PRs. Using the GitHub Action and …
> Workflow updates

- ci/axis/devel.yaml
This PR fixes a typo that we must have all overlooked.
We'll also have to delete the below DockerHub repo that was created as a result and re-publish the latest nightlies.
https://hub.docker.com/r/rapidsai/rapidsai-dev-nighlty/tags
> Fix devel typo

- ci/gpuci/run.sh
This PR reverts a commit on Friday that has been breaking our builds.
The Jenkins agents that run Docker builds do not have `conda` installed and there are no plans to install `conda` at this time. Therefore `gpuci-tools` should be installed via `curl` to prevent builds from breaking.
These changes were tested and confirmed working via a `sed` command in the build below
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/docker/job/rapidsai-base-runtime/54/
> Revert "FIX Update to use conda install instead of curl"

- generated-dockerfiles/centos7-base.Dockerfile
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-base.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Base.dockerfile.j2
- templates/Runtime.dockerfile.j2
- templates/partials/install_notebooks.dockerfile.j2
Previously `runtime` containers FROM-ed `base` where RAPIDS was already installed. The changes made to the build process broke that dependency so we have to install RAPIDS in `runtime` separately.
This is related to an issue that was reported where `import cuml` does not work in `runtime` images. The output from `conda list` does not show `cuml` or any RAPIDS packages are installed with the current `runtime` images. The change in this PR installs RAPIDS to fix this issue.
> FIX Install RAPIDS in `runtime` containers

- generated-dockerfiles/centos7-base.Dockerfile
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-base.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Base.dockerfile.j2
- templates/Runtime.dockerfile.j2
- templates/partials/install_notebooks.dockerfile.j2
`gpuci_conda_retry` already has the `conda` command - so calling `gpuci_conda_retry conda` results in an error of `conda conda` not defined. This removes the extra `conda` defs leaving only `gpuci_conda_retry`
> FIX Remove duplicate conda command

- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Runtime.dockerfile.j2
Similar to a previous fix, the new build process does not FROM `base` for `runtime` containers. So these steps that are taken in the `base` container need to be done in the `runtime` container. This should fix the error that was reported earlier.
#113 corrected the install where RAPIDS is in the container now, but without these additional lines the notebook server and other items do not work as expected.
> FIX Add utils and make `/rapids` dir

- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Runtime.dockerfile.j2
This way the notebook server starts automatically and the images support passing commands like `python -c 'import cuml'`. Without the entrypoint definition the `rapids` conda environment is not activated and we only see the base environment. The `.run_in_rapids` file is overridden with a runtime version in the notebooks install partial template.
> FIX Add entrypoint to `runtime` images

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
This line replaces the script from the notebook install template. Removing it will allow the notebook server to start automatically for the `devel` images.
> FIX Correct ENTRYPOINT for `devel` images

- ci/gpuci/run.sh
The previous selector chose the `centos7` Dockerfiles for `ubuntu16.04` and `ubuntu18.04`. This resulted in errors with the build that prevented the ENTRYPOINT to work correctly and despite local builds working, the produced builds from gpuCI did not have the correct `/rapids` directory and the necessary scripts/notebooks as expected.
I tested these changes in the gpuCI script job and confirmed they work as expected.
> FIX Correct Dockerfile selection in gpuCI script

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
Switched to newer version of ccache and changed the way ccache is installed.
**Reasoning for this:**
- fixes the cmake/ccache error `could not compile a simple test program`
- allows for simple version updates in the future
> [REVIEW] Devel Update Ccache

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-quick.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-quick.Dockerfile
- templates/Devel.dockerfile.j2
- templates/partials/devel_build.dockerfile.j2
Builds off of the recent changes in our forked version of the ccache feedstock https://github.com/rapidsai/ccache-feedstock/pull/1
The version of ccache in the `gpuci-ccache` package is a a specific commit in history which does not bloat ccache and does not not cause the cmake `cannot compile a simple test program` error.
> [REVIEW] Install ccache with forked ccache-feedstock package

- context/.start_jupyter_run_in_rapids.sh
- context/start_jupyter.sh
This PR addresses #133. It enables the `jupyter-lab` server to run in the foreground if the environment variable `JUPYTER_FG` is passed to `docker run`.
i.e: `docker run --gpus all -it -e JUPYTER_FG=true --rm jtest:latest`
and without the var: `docker run --gpus all -it --rm jtest:latest`
Closes #133.
> Enable Jupyter to run in foreground with environment variable

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
Devel builds are failing to find libcumlprims this should fix devel builds while keeping 0.16 images unblocked https://github.com/rapidsai/integration/pull/95
> [REVIEW] Add libcumlprims to conda install

- context/.start_jupyter_run_in_rapids.sh
- context/start_jupyter.sh
Made a few changes which should fix the problem I've found in #133 and also condensed the logic a little.
- Instead of piping to `/dev/tty` I've changed this to not pipe at all.
- Simplified `.start_jupyter_run_in_rapids.sh ` and moved all the foreground/background logic to `start_jupyter.sh`.
- Moved background logic into else statement. I feel this makes things more readable as it's easy to miss the short circuit `exit 0` line.
- Remove the command printing and used `set -x` instead. I've just done this for the one line being printed but it may be helpful to just do this for the whole entrypoint script.
> Removed some if statement duplication and pipe to tty

- context/test.sh
This is needed since newer cugraph NBs require extra datasets.  The script is safe to run multiple times since it only downloads if the files aren't already present.
This is part of a fix for several "file not found" errors from cugraph NBs, another change may still be needed in the NBs themselves.
> [BUG] Run the dataset download script for cugraph prior to running NB tests

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/partials/install_notebooks.dockerfile.j2
This makes sure we always pick up the latest release of nvdashboard. Currently there are conflicts with cuxfilter's bokeh version.
> [REVIEW] Install nvdashboard using conda instead of pip

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/partials/install_notebooks.dockerfile.j2
This PR separates the `source activate rapids` command from the `gpuci_conda_retry install` command. This is because `devel` images have `conda` installed in the `rapids` environment and therefore the wrong `conda` executable gets passed to `gpuci_conda_retry` when the `rapids` environment is activated in `devel` images.
> [REVIEW] [FIX] Fix docker run commands for notebooks

- ci/axis/base-runtime.yaml
- ci/axis/devel.yaml
Simple PR to add CUDA 11 to docker images (devel, base and runtime)
> FEA Add CUDA11 to docker images

- ci/axis/base-runtime.yaml
- ci/axis/devel.yaml
This creates nightly RAPIDS images as burndown started yesterday.
Blocked by: rapidsai/gpuci-build-environment#116
> FIX Add 0.16 RAPIDS to nightly axis

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
This PR adds an environment variable to fix the `cmake`/`ccache` issue that causes the error in builds as shown in the screenshot below. This fix was suggested by @kkraus14 and confirmed working locally.
([src](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/docker/job/rapidsai-devel/110/BUILD_IMAGE=rapidsai%2Frapidsai-dev-nightly,CUDA_VER=10.2,FROM_IMAGE=gpuci%2Frapidsai,IMAGE_TYPE=devel,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_CHANNEL=rapidsai-nightly,RAPIDS_VER=0.16/console))
> Add ENV var to fix ccache/cmake

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
This PR temporarily pins `libcumlprims` to same version as the link below to fix some breaking builds. It should be reverted once a more permanent fix is in place.
https://github.com/rapidsai/cuml/blob/branch-0.16/conda/recipes/libcuml/meta.yaml#L44
> Temporarily pin libcumlprims

- context/entrypoint.sh
#143 overrode the `PATH` variable, which was a bad idea. This PR fixes that change to instead _append_ to the `PATH` variable so that previous `PATH` entries are retained.
> [REVIEW] Update PATH variable

- dockerhub-readme/Dockerhub_rapidsai-dev-nightly.md
- dockerhub-readme/Dockerhub_rapidsai-dev.md
- dockerhub-readme/Dockerhub_rapidsai-nightly.md
- dockerhub-readme/Dockerhub_rapidsai.md
This PR updates the DockerHub docs. I mostly just copied the current DockerHub readmes back to this repo and updated some versions.
Once approved, I'll repaste these changes back to DockerHub.
There's a ton of duplication across these readmes which is annoying to reconcile manually, so we may want to consider Jinja-fying these docs.
Additionally, automating the updates to DockerHub as mentioned in [this card](https://github.com/orgs/rapidsai/projects/9#card-45194062) would be nice too.
> [REVIEW] Update DockerHub docs

- context/entrypoint.sh
This PR moves the `conda activate` command in `entrypoint.sh` above the call to `/opt/docker/bin/entrypoint_source`. This is because some of the commands in `/opt/docker/bin/entrypoint_source` depend on the conda environment (like in [runtime_devel.sh](https://github.com/rapidsai/docker/blob/branch-0.16/context/source_entrypoints/runtime_devel.sh)).
This will resolve a bug where the `jupyter-lab` server does not start automatically in `runtime`/`devel` images.
> Move conda activate command in entrypoint

- context/entrypoint.sh
- context/source_entrypoints/runtime_devel.sh
This PR ensures that the `jupyter-lab` server is run as the new `rapids` user. This is so that any new notebooks made from the Jupyter web dashboard are owned by the `rapids` user instead of the `root` user. This is useful for bind mounts used with the Jupyter-lab server so that files on the host machine aren't owned by `root`.
Additionally, this PR makes some tweaks to the output that is presented to users when running `runtime` & `devel` containers.
Specifically, it instructs users to bind mount to `/rapids/notebooks/host` instead of `/rapids/notebook`. The correct path is `/rapids/notebooks`, not `/rapids/notebook`. The `host` suffix was added because if users mount to `/rapids/notebooks`, then all of the existing RAPIDS notebooks are deleted. By mounting to `/rapids/notebooks/host`, …
> Run jupyter-lab server as rapids user

- context/create_user.sh
There have been some complaints that the new `rapids` user inside of the containers does not have the same privileges as the default `sudo` user that was previously being used. This PR updates the `sudoers` file to give the `rapids` user passwordless `sudo` access to all commands. Since the previous `root` user does not require any passwords for commands, this is the behavior that people have expected for the `rapids` user in our containers.
> Update passwordless sudo for rapids user

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- settings.yaml
This PR updates the xgboost branch to a new branch that has been updated to reflect the recent header-only changes in RMM ([link](https://github.com/rapidsai/rmm/pull/561)).
> Update xgboost branch

- generated-dockerfiles/ubuntu18.04-base.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Base.dockerfile.j2
- templates/Devel.dockerfile.j2
- templates/Runtime.dockerfile.j2
This PR adds the `--no-install-recommends` flag to all of our `apt-get install` commands with the intention of trying to reduce our image sizes.
> Add --no-install-recommends to apt-get installs

- ci/axis/base-runtime.yaml
- ci/axis/devel.yaml
- ci/gpuci/run.sh
Similarly to #175, this PR removes the `RAPIDS_CHANNEL` axis entries since they are not currently being used.
> Remove RAPIDS_CHANNEL in 0.16

- ci/axis/base-runtime.yaml
- ci/axis/devel.yaml
This PR updates the CI axis to build the `0.17` nightlies.
> Update CI axis to build 0.17 nightlies

- context/test.sh
Skip the cugraph benchmarking notebooks.  These notebooks can take half a day to run and are really on-demand notebooks and not for testing
> BUG skip cugraph benchmark notebooks

- dockerhub-readme/Dockerhub_rapidsai-dev-nightly.md
- dockerhub-readme/Dockerhub_rapidsai-nightly.md
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- settings.yaml
- templates/Devel.dockerfile.j2
As indicated by Ray in [this PR](https://github.com/rapidsai/integration/pull/143), `dask-xgboost` was deprecated in `0.15` and should be removed in `0.16`. This PR removes `dask-xgboost` from the Docker `devel` images.
> Remove dask-xgboost (branch-0.16)

- context/test.sh
These notebooks are failing in CI. cusignal devs have brought it to our attention that SDR notebooks require specific hardware and have recommended that we skip these specific notebooks.
> [REVIEW] FIX Add SDR notebooks to skip list

- context/nbtest.sh
This PR ensures that the temp files in `nbtest.sh` are unique.
This is important for CI since the `remote-docker-plugin` volume mounts the `/tmp` directory. This means that during matrix runs (which run in parallel), the `/tmp` directory is shared across all individual matrix jobs.
Additionally, the `mktemp` command also respects the `TMPDIR` environment variable, which is useful for our common `TMPDIR=${WORKSPACE}/tmp` commands.
This PR can quickly be tested by copying and pasting the updated `context/nbtest.sh` file into `/rapids/utils/nbtest.sh` on a `runtime` or `devel` container and then running `/test.sh`.
> Use unique temp files in nbtest.sh

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Devel.dockerfile.j2
- templates/partials/install_notebooks.dockerfile.j2
This PR adds more `gpuci_conda_retry`s throughout the Dockerfile to try to prevent more `conda` errors.
I replaced some `conda remove` commands with `gpuci_conda_retry remove` due to this issue https://github.com/rapidsai/gpuci-tools/issues/14 that I opened which I now suspect was due to `conda remove` not using `gpuci_conda_retry remove`.
> Add gpuci_conda_retries

- blazing-dev/ci/axis/devel.yaml
This PR updates the image name used for Blazing images from `rapidsai/blazingdb-dev` and `rapidsai/blazingdb-dev-nightly` to `rapidsai/blazingsql-dev` and `rapidsai/blazingsql-dev-nightly` respectively.
> Update Blazing DockerHub repo name

- blazing-dev/ci/axis/devel.yaml
This PR updates the `excludes` yaml key for Blazing images. This should've been included in #190
> Update ci axis excludes for Blazing images

- blazing-dev/ci/axis/devel.yaml
This PR adds blazing version 0.17 images to the CI axis.
> Add Blazing 0.17 images to axis

- blazing-dev/ci/axis/devel.yaml
This PR updates the Blazing axis to use `rapidsai/rapidsai-dev` instead of `rapidsai/rapidsai-dev-nightly` as the `FROM_IMAGE` for the `0.16` release.
> Update Blazing Axis - FROM_IMAGE

- generated-dockerfiles/centos7-base.Dockerfile
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-base.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Base.dockerfile.j2
- templates/Devel.dockerfile.j2
- templates/Runtime.dockerfile.j2
- templates/partials/patch.dockerfile.j2
Updates `dot-prop` in the `rapids` conda env to `4.2.1` which is patched for this CVE
> FIX Add patch for CVE-2020-8116

- generated-dockerfiles/centos7-devel.Dockerfile
- templates/Devel.dockerfile.j2
This PR reverts a temporary workaround that was implemented in #109 due to an `xgboost` build issue. The issue was likely fixed upstream since my local builds built successfully without any other action required.
**Note:** This should be merged into the `0.17` branch once it's created. Keeping it as a draft until then to prevent an accidental merge into the `0.16` branch.
> Remove dmlc workaround for centos devel images

- blazing-dev/ci/gpuci/run.sh
- blazing-dev/generated-dockerfiles/centos7-devel.Dockerfile
- blazing-dev/generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- blazing-dev/templates/Devel.dockerfile.j2
- blazing-dev/templates/partials/clone_and_build_blazing.dockerfile.j2
- ci/gpuci/run.sh
- generate_dockerfiles.py
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Devel.dockerfile.j2
- templates/Runtime.dockerfile.j2
- templates/partials/install_notebooks.dockerfile.j2
This PR adds a `BUILD_BRANCH` build argument so that the RAPIDS libraries' `git clone`s use the same branch as the Docker repo.
---
This PR is the same as #207 except that it targets the `main` branch.
> Add BUILD_BRANCH build argument for library clones (hotfix)

- blazing-dev/ci/gpuci/run.sh
- blazing-dev/generated-dockerfiles/centos7-devel.Dockerfile
- blazing-dev/generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- blazing-dev/templates/Devel.dockerfile.j2
- blazing-dev/templates/partials/clone_and_build_blazing.dockerfile.j2
- ci/gpuci/run.sh
- generate_dockerfiles.py
- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/centos7-runtime.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-runtime.Dockerfile
- templates/Devel.dockerfile.j2
- templates/Runtime.dockerfile.j2
- templates/partials/install_notebooks.dockerfile.j2
This PR adds a `BUILD_BRANCH` build argument so that the RAPIDS libraries' `git clone`s use the same branch as the Docker repo.
> Add BUILD_BRANCH build argument for library clones

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- settings.yaml
This PR temporarily removes `cuspatial` from our `devel` images due to some outstanding issues that they're working through.
> Temporarily remove cuspatial

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- settings.yaml
Reverts rapidsai/docker#209. Keith said `cuspatial` has a temporary workaround in place that should allow it to successfully build.
> Revert "Temporarily remove cuspatial"

- generated-dockerfiles/centos7-devel.Dockerfile
- generated-dockerfiles/ubuntu18.04-devel.Dockerfile
- templates/Devel.dockerfile.j2
This PR updates some environment variables that are necessary to make cmake 3.18 work. 
(Thanks Keith and Paul for helping to get this sorted out)
> Update cmake env vars

- context/test.sh
The `E2E_Example.ipynb` notebook requires `pytorch` which we intentionally exclude from our images due to its size. This PR adds the `E2E_Example.ipynb` to our exclusion list.
> Add cusignal notebook exception

- blazing-dev/ci/axis/devel.yaml
- ci/axis/base-runtime.yaml
- ci/axis/devel.yaml
This PR adds the `0.18` images to our axes so we can start getting `0.18` nightlies out.
> Add 0.18 imgs to axes

- generated-dockerfiles/rapidsai_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-runtime.Dockerfile
- templates/rapidsai/Devel.dockerfile.j2
- templates/rapidsai/partials/clone_and_build_blazing.dockerfile.j2
- templates/rapidsai/partials/clone_blazing_notebooks.dockerfile.j2
This PR adds Blazing's notebooks to the `rapidsai` devel images since they were missing. It also switches some of the existing comments to use Jinja comments to prevent them from appearing in the final generated Dockerfiles. This matches the comment style of the rest of the repo.
> Add Blazing notebooks to devel images

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR updates the ubuntu20 and centos8 exclusions since they should not run on anything below CUDA 11.
> Update ubuntu20 & centos8 exclusions

- ci/axis/rapidsai-core-base-runtime.yaml
Missing from the axis files in the new rapids-core files
> FIX Add centos8 & ubuntu20.04 to axis

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
- ci/gpuci/run.sh
This PR includes the following changes:
- Updates the CI axes for `branch-0.18`
- Makes sure the `BUILD_BRANCH` build argument is only set when building the `main` branch. Otherwise, it will default to `branch-${RAPIDS_VER}` as shown [here](https://github.com/rapidsai/docker/blob/branch-0.18/generated-dockerfiles/rapidsai_ubuntu20.04-devel.Dockerfile#L18-L19) (where `RAPIDS_VER` comes from the [axes files](https://github.com/rapidsai/docker/blob/branch-0.18/ci/axis/rapidsai-devel.yaml#L11-L12)). This prevents an issue during burndown where stable and nightly images are being built simultaneously and both sets of images use the stable version as `BUILD_BRANCH` because of how our branching strategy is set up in this repo.
> Update axes & fix BUILD_BRANCH build argument

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- settings.yaml
Syncs our builds with the 0.18 branch of [rapidsai/xgboost](https://github.com/rapidsai/xgboost/tree/rapids-v0.18). This should also fix build errors in devel images as changes were recently pushed to accommodate for RMM updates in early 0.18.
> [REVIEW] FIX Clone correct xgboost branch in docker images for 0.18

- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/gpuci/run.sh
- generate_dockerfiles.py
- generated-dockerfiles/rapidsai-clx_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-clx/Base.dockerfile.j2
- templates/rapidsai-clx/Devel.dockerfile.j2
- templates/rapidsai-clx/Runtime.dockerfile.j2
- templates/rapidsai-clx/partials/cleanup-chmod.dockerfile.j2
- templates/rapidsai-clx/partials/clone_and_build_clx.dockerfile.j2
Add Jinja templates and generated Dockerfiles for CLX images to be published to Docker Hub and NGC.
> CLX templates and dockerfiles

- ci/gpuci/run.sh
It looks like the `docker push` command was commented out for testing purposes in #240 and never reverted. This PR reverts the comment.
> Uncomment docker push for CI

- generated-dockerfiles/rapidsai-clx_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-clx/partials/clone_and_build_clx.dockerfile.j2
CLX is updating to transformers v4 (https://github.com/rapidsai/clx/pull/322).  Doing the same for published CLX devel images.
> Update HuggingFace transformers version for CLX devel images

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai-core/partials/patch.dockerfile.j2
This PR removes an old `npm` security patch. The patch has been causing `devel` build issues and is no longer necessary since `conda` now resolves `nodejs` v15, which has `npm` v7 by default. Additionally, the last few versions of `nodejs` have been patched to address this issue.
> Remove npm patch

- context/source_entrypoints/runtime_devel.sh
Hi!
I have added a small check before displaying the following message, to avoid displaying it if the user has already bound a volume on the right path.
> Make local folders visible by bind mounting to /rapids/notebooks/host
Hope it helps!
Miguel
> Fix #249: Display volume binding message only if not done by the user

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
The recently added rapids-scout-local package removes compiler links on deactivation (intended behavior). This PR moves the ccache env setup after the rapids environment is activated, which should avoid the problem.
> [REVIEW] FIX Move ccache env setup after rapids environment activation

- ci/axis/rapidsai-core-devel.yaml
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
Devel builds are currently running into a "File already exists" error when running the `ln` commands. This happens due to our fixes in the scout repo, so this linking process needs to be removed.
> [REVIEW] Remove unnecessary symlinking for ccache setup

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR adds `0.19` stable images to the exclusions.
> Add 0.19 axis exclusions

- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
This PR updates the DockerHub READMEs for the `0.18` release.
> Update DockerHub READMEs for 0.18 release

- .github/workflows/generated-files.yml
- dockerhub-readme/generate_readmes.py
This PR fixes an issue with the DockerHub README scripts. Currently, the `generate_readmes.py` script deduces the current RAPIDS nightly version from the `DEFAULT_RAPIDS_VERSION` value in [settings.yaml](https://github.com/rapidsai/docker/blob/branch-0.18/settings.yaml#L5). However, when merging PRs to `main` in preparation for a release, the value of `DEFAULT_RAPIDS_VERSION` should be considered the stable version instead of the nightly version.
This PR includes the following changes to fix the above issue:
- Adds a `-n` flag to `generate_readmes.py` so that the nightly value used for generating DockerHub READMEs can be overwritten. It defaults to the value in `settings.yaml`.
- Updates the `generated-files` GitHub Action to increment `DEFAULT_RAPIDS_VERSION` by 1 when testing PRs that …
> Fix DockerHub README Scripts

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
This PR replaces a conda command with `gpuci_conda_retry`. The absence of `gpuci_conda_retry` for this command caused a recent build failure in the `0.18` release ([link](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/docker/job/rapidsai-core-devel/242/BUILD_IMAGE=rapidsai%2Frapidsai-core-dev,CUDA_VER=10.1,FROM_IMAGE=gpuci%2Frapidsai,IMAGE_TYPE=devel,LINUX_VER=ubuntu18.04,PYTHON_VER=3.7,RAPIDS_VER=0.18/console)).
> Add gpuci_conda_retry

- context/source_entrypoints/runtime_devel.sh
- context/start-jupyter.sh
- context/stop-jupyter.sh
- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
- templates/rapidsai-core/partials/os_pkgs.dockerfile.j2
This PR re-adds the `start-jupyter.sh` and `stop-jupyter.sh` scripts that existed before the Jinja2 migration. Multiple people have requested that they be re-added to our images be cause of the convenience they provide. Fixes https://github.com/rapidsai/docs/issues/160.
Additionally, it removes a call to `yum check-updates` that existed before `yum install`. The `yum check-updates` command will exit with a `100` error code if there are updates available on the machine ([src](https://access.redhat.com/solutions/2779441)). This was causing issues when trying to test these changes locally (though I'm not sure why it didn't show up in our nightly builds). From examining the `yum install` output though, it looks like `yum install` checks for updates anyway, so the explicit `yum check-updates` …
> Add start/stop Jupyter scripts

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai-core/partials/patch.dockerfile.j2
Reverts rapidsai/docker#248
We still need to update `npm` to at least version 7 due to some CVE notices with installed `npm` pkgs. This is preventing the 0.18 hotfix images from being accepted by NGC
> Revert "Remove npm patch"

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
This adds the `apt-get upgrade` layer to our Base/Runtime and Devel images. Dask-cudf unit tests were tested as well so hopefully this will allow us to pass scans for NGC.
> [REVIEW] FIX Add apt-get upgrade layer

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
This PR removes the `nightly` channels from our `.condarc` file when building `stable` builds.
> Remove nightly channels from stable builds

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
Upstream nvidia/cuda now has CUDA 11.2 CentOS 7 builds, so we can remove the exclusions to build them now
> FIX Enable CUDA 11.2 CentOS 7 builds

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai/partials/clone_and_build_blazing.dockerfile.j2
Removes ccache from devel images for now. The ccache folder is bloating containers by about 2GB. The functionality will be re-enabled in the future once `scout` packages have S3 integration.
> [REVIEW] FIX Remove ccache image bloating

- ci/gpuci/run.sh
Currently builds could use a cache while building, this ensures all builds are fresh.
> [REVIEW] FIX Don't use a cache when building

- .github/workflows/generated-files.yml
This PR changes the shell from `sh` to `bash` for the `generated-files.yml` GitHub Action. This should resolve the `sh: let: not found` error linked below.
https://github.com/rapidsai/docker/pull/293/checks?check_run_id=2336856577
> Change shell for GH Action

- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
This PR updates the READMEs for DockerHub to reflect the correct image variants available in DockerHub vs. ngc.
It also adds a reference to CUDA `11.2` support.
> Update DockerHub READMEs

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/patch.dockerfile.j2
This change removes stray folders in `/tmp` that contain cached versions of vulnerable packages that aren't caught when updating node.
> [REVIEW] FIX Remove cached npm packages

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
- templates/rapidsai-core/partials/patch.dockerfile.j2
This PR includes the following changes:
- Adds cache clean commands (`juptyter lab clean && jlpm cache clean`) to remove vulnerable `npm` packages
- Changes the `npm` version spec since the latest version `7.11.0` has [a bug](https://github.com/npm/cli/issues/3132) that prevents builds from completing successfully
> Clean Jupyter Cache

- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/templates/base.md.j2
Includes the following changes:
- Remove `blazingsql` mention in NGC README
- Remove DockerHub _additional OS_ mention from NGC since we now push Centos 8 and Ubuntu 20.04 to NGC
> Update ngc README

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
After updating to JupyterLab 3 in https://github.com/rapidsai/jupyterlab-nvdashboard/pull/85 and https://github.com/rapidsai/integration/pull/261, the JupyterLab extensions in this PR no longer need to be installed via `jupyter labextension install` and can instead be installed solely through `conda`.
This should fix the `runtime` and `devel` build errors shown [here](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/docker/job/rapidsai-core-devel/438/BUILD_IMAGE=rapidsai%2Frapidsai-core-dev-nightly,CUDA_VER=11.0,FROM_IMAGE=gpuci%2Frapidsai,IMAGE_TYPE=devel,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=0.20/console)
This PR depends on https://github.com/rapidsai/integration/pull/266
> JupyterLab 3 Updates

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/patch.dockerfile.j2
The `<7.11` specifier for `npm` was introduced in #312 since `npm` version `7.11.0` had [a bug](https://github.com/npm/cli/issues/3132) at the time. The bug has since been fixed in `7.11.1`, so this upper version limit should be able to be safely removed now.
> Remove `npm` upper version limit

- context/test.sh
Notebook is not needed in matrix tests.
> Skip random_walk_perf notebook

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/partials/os_pkgs.dockerfile.j2
This PR adds the `libsnl` dependency to CentOS images, which is required for some `cuxfilter` notebooks to run correctly. This PR should fix the `ImportError: libnsl.so.1: cannot open shared object file: No such file or directory` error in the notebook test job log below.
https://gpuci.gpuopenanalytics.com/view/RAPIDS%20Tests%20-%20Nightly/job/rapidsai/job/nightly-tests/job/docker-test-notebooks/CUDA_VER=11.2,LINUX_VER=centos8,PYTHON_VER=3.7,RAPIDS_VER=0.20,RUNTIME_DOCKER_REPO=rapidsai%2Frapidsai-nightly/578/consoleFull
> Add `libsnl` to CentOS images 

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
This PR update the build command used for `cuml`. They recently removed the `--buildgtest` flag in the PR below.
https://github.com/rapidsai/cuml/pull/3844/files#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823L42
> Update `cuml` build command

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
Nightly tests require this package to run cugraph tests. This is a temporary change until we update to a more permanent fix in the package dependencies.
> [REVIEW] Add rapids-pytest-benchmark to devel images

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR adds `21.08` to the build axes so that the `21.08` images start building.
> Add `21.08` to axes

- context/.condarc
including the defaults channel could trigger anaconda's terms of service (https://www.anaconda.com/terms-of-service), which adds complexity for the end user
$ docker run --rm rapidsai/rapidsai:0.19-cuda11.2-base-ubuntu20.04-py3.8 conda list -c | grep -e defaults -e main
defaults/linux-64::aws-sdk-cpp-1.8.151-hce553d0_0
$ docker run --rm rapidsai/rapidsai:0.19-cuda11.2-runtime-ubuntu20.04-py3.8 conda list -c | grep -e defaults -e main
defaults/linux-64::scipy-1.6.0-py38hf56f3a7_0
the aws-sdk-cpp and scipy packages have analogs in the conda-forge channel
> remove defaults channel

- context/source_entrypoints/runtime_devel.sh
- context/start-jupyter.sh
This is required to allow Jupyter to be accessible from behind a reverse proxy with a URL. Otherwise only localhost and IP address connections are accepted.
> Allow Jupyter Lab connections from any origin

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
Reverts #330 which was an attempt at getting pytest benchmark into the images to allow cugraph testing. Conda incorrectly was labeling `librmm` with 21.08 in the image which could result in confusion. Alternative approach is to update the conda package in the benchmark repo and install in the test script.
> [REVIEW] Revert 330: Remove pytest plugin from devel

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- settings.yaml
- templates/rapidsai-core/Devel.dockerfile.j2
Source installs rapids-pytest-benchmark to avoid installing multiple RMM packages within the rapids environment.
> [REVIEW] FIX Source build rapids-pytest-benchmark

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- settings.yaml
This PR prepares `branch-21.06` for the `21.06` release. It should be merged right before we open/merge the PR from `branch-21.06` into `main`.
> Prepare 21.06 release

- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
Since the `#prerequisites` anchor link does not work on Docker Hub or NGC, remove it to avoid confusion for users.
> Remove prereq link

- context/entrypoint.sh
Add option to disable quoting in entrypoint exec
Usage:
```
docker run <image>:<tag> --unquote-exec "cmd"
docker run -e UNQUOTE_EXEC=true <image>:<tag> "cmd"
```
> Add option to disable quoting in entrypoint exec

- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/os_pkgs.dockerfile.j2
The `libopenmpi-dev` package doesn't have the necessary binaries for OpenMPI, so add the binaries package.
CentOS has the necessary binaries already:
```
$ docker run -it --rm rapidsai/rapidsai-core-nightly:21.08-cuda11.0-base-centos8 find / -name mpirun
/usr/lib64/openmpi/bin/mpirun
```
> Add openmpi-bin to Ubuntu images

- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
Adds some documentation to help people that want to build images on top of the RAPIDS images.
People have been vocal about facing issues working with RAPIDS images and finding it difficult to properly run their commands in the right environment. Due to its generality, it is also hard to find a solution in the public domain, so directly addressing it in our README should make it easier for users who are interested in doing this.
This README is linked on our homepage under `Getting Started`, so this won't be added specifically to the site.
> [REVIEW] DOC Add documentation snippet about rapids environment

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- settings.yaml
- templates/rapidsai-core/Devel.dockerfile.j2
The [rapidsai/xgboost](https://github.com/rapidsai/xgboost/tree/branch-21.08) repo's default branch name was recently updated from `rapids-v21.08` to `branch-21.08` in order to match the branch names of other RAPIDS libraries. This PR updates the Dockerfiles to use this updated branch name.
> Update `xgboost` branch logic

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
This PR removes the temporary workaround for `xgboost` that was added in #243. It can be removed now that https://github.com/dmlc/treelite/issues/244 is closed.
> Remove `xgboost` workaround

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu16.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/patch.dockerfile.j2
This PR adds some temporary fixes for some CVEs that were detected in our images.
While the `pip install --upgrade` commands address the CVEs, we should ultimately update our miniconda installation version which has these CVEs addressed out of the box. This would consist of updating the `CONDA_VER` arg here: https://github.com/rapidsai/gpuci-build-environment/blob/78ba8b94ac693d7c7b408fe4ddb1097a2c37b8f1/miniconda-cuda/Dockerfile#L12-L14
> Address `21.06` CVEs

- generated-dockerfiles/rapidsai-core_centos7-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai-core/partials/patch.dockerfile.j2
With https://github.com/rapidsai/gpuci-build-environment/pull/198 merged and published, the manual package updates that were done in #348 are no longer necessary. This PR reverts the updates since the new version of `miniconda` includes patched versions out-of-the-box.
> Revert "Merge pull request #348 from ajschmidt8/21.06-cves"

- context/source_entrypoints/runtime_devel.sh
- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
This PR updates the `runtime`/`devel` entrypoint to support a new argument, `DISABLE_JUPYTER`, which disables the default Jupyter server from running when the container starts
> Update `runtime`/`devel` entrypoint

- context/packages.sh
- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
Adds a timeout to each of the package install commands which default to 10 minutes but can be set with the environment variables `APT_TIMEOUT`, `YUM_TIMEOUT`, `CONDA_TIMEOUT` and `PIP_TIMEOUT`.
Possibly closes #365
> Add configurable timeouts to package install commands

- generated-dockerfiles/rapidsai_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai_centos7-runtime.Dockerfile
- generated-dockerfiles/rapidsai_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai_centos8-runtime.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-runtime.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-runtime.Dockerfile
- templates/rapidsai/partials/clone_blazing_notebooks.dockerfile.j2
The notebook testing files were removed in #362, so this PR removes a leftover `COPY` command that references the `test.sh` file that no longer exists.
> Remove references to `test.sh`

- generated-dockerfiles/rapidsai_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-devel.Dockerfile
- templates/rapidsai/partials/clone_and_build_blazing.dockerfile.j2
Since the RAPIDS team has taken over maintenance of Blazing for the `21.10` release, this PR updates the URL that's used to clone Blazing in our `devel` images.
> Update Blazing URL

- generated-dockerfiles/rapidsai_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-devel.Dockerfile
- templates/rapidsai/partials/clone_and_build_blazing.dockerfile.j2
This PR is a continuation of #371. Since our forked Blazing repository has a different name than the source repository, this PR ensures that the fork is cloned into a folder that has the same name as the source repository.
> Update Blazing Clone Directory

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR updates the axes files to build and publish the `21.12` nightlies.
> Update axes files to publish `21.12` nightlies

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-devel.yaml
Since BlazingSQL will be removed from RAPIDS in `21.12`, the `rapidsai` images (i.e. non-core images) do not need to be built for `21.12` and can therefore be removed from the axes files here.
This will prevent CI failures from occurring when trying to build/install Blazing for `21.12`.
> Remove `21.12` axis from `rapidsai` images

- ci/axis/rapidsai-core-devel.yaml
This PR updates the `UCX_PY_VER` value for `devel` containers. The `ucx-py` version used for `branch-21.10` should be `0.22` instead of `0.21`. See https://github.com/rapidsai/cudf/pull/9099 for reference.
> Update `UCX_PY_VER` Value

- generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
This PR updates the `cugraph` build step to ensure that it also builds the new `pylibcugraph` library.
> Update `cugraph` build step

- generated-dockerfiles/rapidsai-clx_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-clx_ubuntu20.04-runtime.amd64.Dockerfile
- templates/rapidsai-clx/Runtime.dockerfile.j2
- templates/rapidsai-clx/partials/clone_and_build_clx.dockerfile.j2
- Update PyTorch 1.7.1 to latest stable (1.10). 
- pip install latest stable PyTorch (v1.10) in `base` and `devel` images. Replaces conda install of PyTorch 1.7.1 which was tying us to CUDA 11.0. conda and mamba would often install cpu version of PyTorch on RAPIDS-supported CUDA versions.
- Fixes `runtime` containers which had cpu PyTorch installed.
> Update CLX Dockerfiles to pip install PyTorch

- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
This PR updates the axes to release `22.02` images.
> Update axes to release `22.02` images

- ci/gpuci/run.sh
This PR adds the `DASK_SQL_VER` build argument, which is currently absent and therefore causing issues when trying to clone the `dask-sql` repository in our Docker builds.
The `DASK_SQL_VER` is populated via the matrix configuration files (i.e. `ci/axis/rapids-devel.yaml`).
> Add `DASK_SQL_VER` Docker build argument

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
- dockerhub-readme/generated-readmes/ngc.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx-dev.md
- dockerhub-readme/generated-readmes/rapidsai-clx-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-clx.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core-dev.md
- dockerhub-readme/generated-readmes/rapidsai-core-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-core.md
- dockerhub-readme/generated-readmes/rapidsai-dev-nightly.md
- dockerhub-readme/generated-readmes/rapidsai-dev.md
- dockerhub-readme/generated-readmes/rapidsai-nightly.md
- dockerhub-readme/generated-readmes/rapidsai.md
- dockerhub-readme/templates/base.md.j2
This PR updates the axis files for the release. It removes `22.02` from the axes and adds `-nightly` to the `excludes` so that the resulting image names do not have the `-nightly` suffix.
Hold off on merging this until we're ready to release the images.
> Prepare Axis Files for Release

- RELEASE.md
This PR adds a reminder about merging the `notebooks` repo release PR to `RELEASE.md` since our images depend on the `notebooks` repository being up-to-date.
> Add note about `notebooks` repo to `RELEASE.md`

- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/gpuci/run.sh
After #413 was merged, the Jenkins jobs had to be updated to remove `UCX_PY_VER` from the axis. Therefore, `branch-21.12` builds stopped working. This PR should resolve that by backporting #413 to `branch-21.12`.
The `generated-files` check is expected to failed on this PR.
> Backport #413 to `branch-21.12`

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
This PR adds the `ptxcompiler` package to our `devel` images.
The `generated-files` check is expected to fail for this PR.
> Add `ptxcompiler` package to `devel` images

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
This reverts commit 4d71e44a55caaa070e2ec29ddf8c132ce451dd66 on `branch-22.02`. The PR below supersedes the commit that is being reverted.
- https://github.com/rapidsai/integration/pull/403
> Revert "Add `ptxcompiler` package to `devel` images"

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
After https://github.com/rapidsai/integration/pull/411 was merged, the build string for our meta-packages changed from `cuda11.5*` to just `cuda11*`. This change caused our Docker builds to stop working.
Since we now build with CUDA Enhanced Compatibility, I think it should be fine to drop the `=cuda` spec from the strings below. However, an alternative would be to include the `cudatoolkit` spec as shown below, but I don't think that's necessary. 
```sh
gpuci_mamba_retry install -n rapids \
"rapids-notebook-env=${RAPIDS_VER}" \
"cudatoolkit=${CUDA_VER}*" \
&& gpuci_conda_retry remove -y -n rapids --force-remove \
"rapids-notebook-env=${RAPIDS_VER}*"
```
@Ethyling, any thoughts here?
> Fix package specifications

- context/source_entrypoints/runtime_devel.sh
When you run the RAPIDS runtime docker images interactively they start Jupyter as a background process and drop you into a bash shell which is nice for folks running the container via the CLI interactively.
However when trying to use the Docker image non-interactively in services like Binder, Kubeflow, Kubernetes, Dask Clusters, etc this is a bit of a hinderance. A while back we added a `JUPYTER_FG` env flag to run Jupyter in the foreground and a `DISABLE_JUPYTER` env flag to disable Jupyter all together. These workarounds are useful but it would be really great for the docker image to run successfully in a non-interactive environment without additional configuration.
**Reproducer**
```console
$ docker run --rm rapidsai/rapidsai-core:21.12-cuda11.5-runtime-ubuntu20.04-py3.8
$ docker run …
```
> Run Jupyter in foreground if non-interactive

- context/source_entrypoints/runtime_devel.sh
- context/start-jupyter.sh
Some spawning environments such as [the one used in Kubeflow](https://www.kubeflow.org/docs/components/notebooks/container-images/#image-requirements) expect to set an `NB_PREFIX` environment variable when proxying the Jupyter server so that Jupyter handles requests correctly.
Updating the `jupyter lab` command to handle this.
> Handle NB_PREFIX in Jupyter startup

- generated-dockerfiles/rapidsai_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-devel.amd64.Dockerfile
- templates/rapidsai/partials/clone_and_build_dask-sql.dockerfile.j2
Once https://github.com/dask-contrib/dask-sql/pull/396 is merged in, the build commands for dask-sql will change so that the Java extensions must be built separately from the `pip` install. This PR updates the build commands for the `devel` images accordingly.
> Update dask-sql build commands

- generated-dockerfiles/rapidsai_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-devel.amd64.Dockerfile
- templates/rapidsai/partials/clone_and_build_dask-sql.dockerfile.j2
With https://github.com/dask-contrib/dask-sql/pull/406, we should be able to consolidate the build command for dask-sql so that we no longer need to run `python setup.py java` for a source installation.
Needs https://github.com/dask-contrib/dask-sql/pull/406
> Update dask-sql build command for `devel` images

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
The `libcugraphops` package is necessary for `cugraph` to build. `libcugraphops` is a private repo though, so this just installs it via `conda` which is similar to what we do for `cumlprims`.
> Add `libcugraphops`

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
Use `mamba` to install `jupyterlab-nvdashboard`. This is fixing some build issues with `arm64`
> Use mamba to install jupyterlab-nvdashboard

- generated-dockerfiles/rapidsai_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-devel.amd64.Dockerfile
- templates/rapidsai/partials/clone_and_build_dask-sql.dockerfile.j2
This PR removes the `~/.m2` directory from the images after the `dask-sql` source build. This change is necessary because the `~/.m2` directory contains `log4j`, which triggers some security alerts for our images. As per @jdye64, the `log4j` dependency is only used during the compile steps (and is not in the resulting `DaskSQL.jar` file) and is therefore safe to simply remove with `rm -rf ~/.m2`.
> Remove `~/.m2` directory after `dask-sql` source build

- .github/workflows/update-dask-sql.yml
Adds a GHA workflow that checks for a new dask-sql version nightly, opening a PR if a new one is detected updating all relevant files in this repo.
> Add workflow to automate dask-sql updates

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
This PR backports #437 to `branch-22.02` to help resolve/deubg some `conda` conflicts that occur when installing `jupyterlab-nvdashboard`.
> [HOTFIX] Backport #437 to `branch-22.02`

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
As a workaround for issues raised in #438 and #439 this PR sets the `PATH` explicitly to include the RAPIDS conda environment.
Many container platforms including Kubernetes override the default entrypoint, so this change ensures binaries like `jupyter` are still on the path even without the entrypoint being run. Also when calling `docker exec` on a container the environment is not copied from the main process and without the entrypoint the path is also wrong.
> Set the default PATH to include the RAPIDS conda env

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
This PR updates the changes made in #449 to re-order the `PATH` values. Before this change, there were some issues occurring on the `devel` images where `conda` was assuming the base environment was `/opt/conda/envs/rapids` instead of `/opt/conda`.
> Fix `PATH` variable

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- templates/rapidsai-core/partials/entrypoint.dockerfile.j2
This PR removes the `PATH` override from the `devel` images since it seems to be causing issues with them.
> Remove `PATH` override from `devel` images 

- context/source_entrypoints/runtime_devel.sh
This PR adds exceptions for `jupyter kernelspec` and `ipykernel` commands to be executed in runnable docker configurations like the following:
> docker run --rm --name foobar quasiben/vertexai-exec:1 /opt/conda/envs/rapids/bin/python -m ipykernel_launcher foobar
> docker run --rm --name foobar quasiben/vertexai-exec:1 jupyter kernelspec list --json
---
This PR is just #466 cut from `branch-22.04`.
> exec jupyter kernelspec and ipykernel commands

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/Base.dockerfile.j2
- templates/rapidsai-core/Devel.dockerfile.j2
- templates/rapidsai-core/Runtime.dockerfile.j2
- templates/rapidsai-core/partials/os_pkgs.dockerfile.j2
This PR backports the recent `apt` key fix that we implemented in https://github.com/rapidsai/gpuci-build-environment/pull/255 to the stable `22.04` images.
> `apt` key fix

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This PR updates our CI axes to build the `22.10` images.
> Update axes to build `22.10` images

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
⚠️ This PR should be merged to `branch-22.10` once that branch exists.
This enables (retains support for) Arrow S3 in Docker builds of libcudf. PR https://github.com/rapidsai/cudf/pull/11470 changed the default behavior, turning the feature off.
See https://github.com/rapidsai/cudf/pull/11470#pullrequestreview-1063942110 / cc: @ajschmidt8
> Enable Arrow S3 support for libcudf.

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/patch.dockerfile.j2
`nbconvert-core` restricts `mistune` to `<2`, so this attempt at upgrading `mistune` fails.
See [build log](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/docker/job/rapidsai-core-base-runtime/1067/BUILD_IMAGE=rapidsai%2Frapidsai-core,CUDA_VER=11.5,FROM_IMAGE=gpuci%2Frapidsai,IMAGE_TYPE=base,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=22.08/console)
> Revert mistune upgrade due to incompatibility

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
Since https://github.com/rapidsai/raft/pull/801 was merged, we need to update our build commands accordingly for `raft`.
> Update `raft` build command

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
The `--install` flag removed [here](https://github.com/rapidsai/raft/pull/1026/files) causes the `rapidsai/rapidsai-core-dev-nightly` image build to fail.
> update raft build cmd

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/os_pkgs.dockerfile.j2
The rockylinux `core-dev-nightly` are failing to build due to this error: `xargs: command not found`. Adding this package should solve the issue.
> Install `xargs` for rockylinux

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
Without this `openssl` pin, our `openssl` version gets upgraded to version `3.0.7` from version `1.1.1`, which seems to cause CMake build issues for our `devel` containers.
This PR pins `openssl` to `1.1.1` to prevent these build issues.
> [HOTFIX] Pin `openssl` version

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-runtime.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/install_notebooks.dockerfile.j2
This work around is implemented to stop `pyarrow` from upgrading to version 10 as this creates a conflict against the required RAPIDS preference of version 9.
> fix: freeze installed

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu18.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
Adds additional targets to the `cugraph` build to include newer components that are expected to be built by the `docs` build and cugraph devs using these images.
This depends on https://github.com/rapidsai/integration/pull/584
> Adds additional targets to cugraph build 

- generated-dockerfiles/rapidsai-core_centos7-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_centos7-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-base.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-base.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-runtime.arm64.Dockerfile
- templates/rapidsai-core/partials/os_pkgs.dockerfile.j2
Reverts rapidsai/docker#510
Since we don't build `devel` containers for `rockylinux` anymore, we can revert this change.
> Revert "Install `xargs` for rockylinux"

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-clx-base-runtime.yaml
- ci/axis/rapidsai-clx-devel.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
This prevents building the non-nightly images for 23.04
> Add excludes for 23.04

- .github/workflows/generated-files.yml
This PR updates the `generated-files` workflow to remove the `python` container, which was causing an issue due to using an outdated version of `git`.
> Fix broken GHA workflow

- generated-dockerfiles/rapidsai-core_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_rockylinux8-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu20.04-devel.arm64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu22.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai-core_ubuntu22.04-devel.arm64.Dockerfile
- templates/rapidsai-core/Devel.dockerfile.j2
Due to the changes in https://github.com/rapidsai/raft/pull/1333, the `libraft` build command in our `devel` containers need to be updated.
This should only be merged after https://github.com/rapidsai/raft/pull/1333.
> Update `libraft` build command

- .github/ops-bot.yaml
Adds the `ops-bot.yaml` config enabling `copy_prs`. This is required support GitHub Actions CI required by #539.
After this is merged, I will cut `branch-23.06`.
> Add ops-bot config

- .github/workflows/update-dask-sql.yml
- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-devel.yaml
As discussed a while ago with @ajschmidt8, we are erroneously installing the stable version of Dask-SQL in our nightly containers.
This PR makes some modifications to the version specification and workflow updating these specifications so that we will now properly install the nightly version in these containers as expected.
> Refactor dask-sql updating workflow to use shortened version for `DASK_SQL_VER`

- ci/axis/rapidsai-devel.yaml
- generated-dockerfiles/rapidsai_centos7-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_rockylinux8-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu20.04-devel.amd64.Dockerfile
- generated-dockerfiles/rapidsai_ubuntu22.04-devel.amd64.Dockerfile
- templates/rapidsai/partials/clone_and_build_dask-sql.dockerfile.j2
Follow up from #541 
Since the devel build uses the `DASK_SQL_VER` to pick which branch or tag to clone, it must use the full version to successfully clone https://github.com/dask-contrib/dask-sql/tree/2023.2.0
Also strips the patch version from `DASK_SQL_VER` when installing the dependencies via `mamba`.
See a recent failed build [here](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/docker/job/rapidsai-devel/797/BUILD_IMAGE=rapidsai%2Frapidsai-dev-nightly,CUDA_VER=11.8,DASK_SQL_VER=2023.2,FROM_IMAGE=rapidsai%2Frapidsai-core-dev-nightly,IMAGE_TYPE=devel,LINUX_VER=ubuntu22.04,PYTHON_VER=3.10,RAPIDS_VER=23.04/console)
> Use full version for dask-sql

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
This is just to unblock existing builds until #545 can be merged.
> Update Python to 3.9

- ci/axis/rapidsai-core-base-runtime-arm64.yaml
Due a bug in `glibc` (https://bugzilla.redhat.com/show_bug.cgi?id=1722181) which affects `2.31`, we can't publish an `arm64` `ubuntu20.04` image since it ships with `glibc` `2.31`. `x86_64` images are not affected.
This is the error when trying to work with `cuml` or `cugraph`: `ImportError: /opt/conda/envs/rapids/lib/python3.9/site-packages/cuml/internals/../../../.././libgomp.so.1: cannot allocate memory in static TLS block`
`glibc` versions:
- `ubuntu20.04` - 2.31
- `ubuntu22.04` - 2.35
- `rockylinux8` - 2.28
> Drop ubuntu20.04 from arm64 images

- ci/axis/rapidsai-base-runtime.yaml
- ci/axis/rapidsai-core-base-runtime-arm64.yaml
- ci/axis/rapidsai-core-base-runtime.yaml
- ci/axis/rapidsai-core-devel-arm64.yaml
- ci/axis/rapidsai-core-devel.yaml
- ci/axis/rapidsai-devel.yaml
I disabled the Jenkins jobs to build `branch-23.08` and will re-enable after this PR is merged to prevent `23.08` images from being pushed to stable docker repos.
Ref #553
> Enable 23.08 nightly builds

- .github/workflows/build-test-publish-images.yml
Since nightly tests are not yet enabled, the `build-multiarch-manifest` job should run without the `test` job. This will ensure nightly images are pushed to Docker Hub.
Skipping CI since this job does not run on PRs.
> Publish multiarch images w/o tests

- context/notebooks.sh
Internal discussions resulted that just `cudf`, `cuml`, `cugraph`, & `cuspatial` notebooks should be tested.
We might exclude more notebooks and will iterate on this PR.
> Remove repos that should not be notebook tested

- .github/workflows/build-test-publish-images.yml
- .github/workflows/pr.yml
- .github/workflows/publish.yml
- .github/workflows/test-notebooks.yml
- matrix-test.yaml
Refactoring how tests are triggered to use an input. This will allow a calling workflow in `rapidsai/actions` to execute the notebook tests on a nightly basis.
> Add input to enable testing

- .github/workflows/update-dask-sql.yml
This PR updated the `update-dask-sql.yml` workflow. This should resolve the previous failures such as https://github.com/rapidsai/docker/actions/runs/5756838849/job/15606942103
Changes:
- `the-coding-turtle/ga-yaml-parser` uses deprecated `::set-output`, so switching to use `yq` & `$GITHUB_OUTPUT` instead. This requires using the `rapidai/ci:latest` container so `yq` is available.
- Minor clean up for versions & PR text
- Updates the checkout action version
> Updates to the `update-dask-sql.yml` workflow

- .github/workflows/update-dask-sql.yml
Forward-merge triggered by push to `branch-23.08` that creates a PR to keep `branch-23.10` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.08 to branch-23.10

- .github/workflows/build-test-publish-images.yml
Small change to ensure that the temp images aren't deleted until after tests are run.
> Ensure tests run before deleting temp imags

- .github/workflows/test-notebooks.yml
Not 100% sure why, but [starting recently](https://github.com/rapidsai/docker/actions/runs/5923767292/job/16060805130#step:4:8), `curl` is no longer available in the `notebooks` image during tests.
This PR ensures `curl` & `git` are installed before installing `gha-tools` and running tests. Using `--freeze-installed` ensures the tests run on the same environment that is published with the exception of `curl`, `git`, and `perl` (dependency of `git`) being present, but those packages should not impact the tests.
> Ensure curl is installed before `gha-tools`

- Dockerfile
Closes #587
Adds `--NotebookApp.base_url="${NB_PREFIX:-/}"` to the `jupyter-lab` `CMD` in the `notebooks` image. Since this relies on an environment variable, the `CMD` has to be switched to invoke a shell. See: https://docs.docker.com/engine/reference/builder/#cmd
I think this was missed during the overhaul.
xref: #426
> Add NotebookApp.base_url to jupyter-lab command

- Dockerfile
- context/notebooks.sh
Forward-merge triggered by push to `branch-23.10` that creates a PR to keep `branch-23.12` up-to-date. If this PR is unable to be immediately merged due to conflicts, it will remain open for the team to manually merge.
> Forward-merge branch-23.10 to branch-23.12

- .github/workflows/build-image.yml
PR enables AARCH64 raft-ann-bench* images and fixes the multiarch GHA jobs.
> Enable AARCH64 raft-ann-bench images

- ci/compute-matrix.jq
- matrix-test.yaml
Update `compute-matrix.jq` to allow for CUDA 12 arm64 builds.
Also modifies the test matrix for CUDA 12 arm64 based on https://github.com/rapidsai/shared-action-workflows/blob/branch-23.12/.github/workflows/conda-python-tests.yaml.
> Add CUDA 12 arm64 to the matrix

- .github/workflows/test-notebooks.yml
- ci/release/update-version.sh
Update `shared-action-workflows` references to `shared-actions` following the work to rename the `rapidsai/shared-action-workflows` to `rapidsai/shared-workflows`.
> Update `shared-action-workflows` references

- raft-ann-bench/cpu/Dockerfile
- raft-ann-bench/gpu/Dockerfile
PR installs perl on RAFT benchmark containers since there are still some legacy scripts that need it.
> Install perl temporarily on RAFT benchmark containers

- .github/workflows/test-notebooks.yml
Updates the reference to the shared `rapids-github-info` action to use the new `rapidsai/shared-actions` repository.
> use new shared-actions repo

- Dockerfile
- dockerhub-readme.md
We're renaming our mambaforge images to miniforge as described in [this PR](https://github.com/rapidsai/mambaforge-cuda/pull/51). This PR updates the old references in this repository.
> Update mambaforge to miniforge

- ci/release/update-version.sh
Updates the `update-version.sh` for a couple changes.
Skipping CI since this file is not testing by CI.
> Fix update-version script

- matrix-test.yaml
- matrix.yaml
As communicated in RSN 35, this removes CUDA 11.2 from the Docker support matrix.
https://docs.rapids.ai/notices/rsn0035/
> Drop CUDA 11.2 from Docker matrix.

- Dockerfile
Fixes attempted in https://github.com/rapidsai/integration/pull/695 & https://github.com/rapidsai/integration/pull/697 don't play well with CEC at large, but this repo can pin `cuda-python` more restrictively.
This PR pins `cuda-python` to the CUDA `major.minor.*` version.
See also https://github.com/conda-forge/cuda-python-feedstock/issues/66
> Pin cuda-python

- Dockerfile
Now that `cuda-python` packaging has been fixed to enable CUDA Enhanced Compatibility in https://github.com/conda-forge/cuda-python-feedstock/pull/67, we can unpin `cuda-python` in our Docker builds. This reverts commit 7c808e762eb73de09900fe2d692d6b0c5e80d6f2.
> Revert "Pin cuda-python (#624)"

- dockerhub-readme.md
`cusignal` is no longer included in the images.
> Remove deprecated cusignal from package list

- Dockerfile
- dockerhub-readme.md
- matrix-test.yaml
- matrix.yaml
- raft-ann-bench/README.md
- raft-ann-bench/cpu/Dockerfile
- raft-ann-bench/gpu/Dockerfile
Adds support for Python 3.11.
xref: https://github.com/rapidsai/build-planning/issues/3
> Add Python 3.11.

- renovate.json
This PR adds a once-a-month schedule for `renovate` to avoid excessive PR noise.
See their noise-reduction guide here for additional details: https://docs.renovatebot.com/noise-reduction/
> Add `renovate` schedule

- Dockerfile
`jupyterlab-nvdashboard` is going to release `0.10.0` soon which requires `jupyterlab>=4`.
Since RAPIDS `24.04` is being released today/tomorrow, we don't want to update `jupyterlab` to 4, so this PR pins `jupyterlab-nvdashboard==0.9.*`.
For `24.06`, we can unpin this and also upgrade to `jupyterlab` 4.
> Pin jupyterlab-nvdashboard to `0.9`

- context/test_notebooks.py
PR updates `test_notebooks.py` to skip  `cuspatial` notebooks which aren't being run in ci
> Skip cuspatial notebook tests

- CONTRIBUTING.md
- README.md
The links to docker hub still pointed to the deprecated images. This pull request updates the links to point to the current images.
Fixes issue #661
> Fix links to docker hub in README.md

- dockerhub-readme.md
The rapids metapackage was updated to include `cuvs` by https://github.com/rapidsai/integration/pull/708, so add it to the list in the readme.
> Add cuvs to list of libraries

- .github/CODEOWNERS
This PR overhauls how `ops-codeowners` reviews are handled.
`ops-codeowners` is replaced by `ci-codeowners` & `packaging-codeowners`. The coverage of files is expanded as well.
Additionally, the process will change: reviews will be assigned to a member of the teams instead of a manual request to `ops-codeowners`.
> Adopt packaging codeowners

- context/notebooks.sh
Contributes to https://github.com/rapidsai/dependency-file-generator/issues/89
Resolves this warning from `rapids-dependency-file-generator`.
> /opt/conda/lib/python3.9/site-packages/rapids_dependency_file_generator/cli.py:98: UserWarning: The use of --file_key is deprecated. Use -f or --file-key instead.
> resolve file_key deprecation warning from rapids-dependency-file-generator

- Dockerfile
Upgrading the `notebooks` image to use `jupyterlab`4. This allows for unpinning `jupyterlab-nvdashboard` as well.
Also switches installing `jupyterlab-nvdashboard` from `pip` to `conda` which seems to work now and would close https://github.com/rapidsai/jupyterlab-nvdashboard/issues/156.
> Migrate to jupyterlab 4

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/pr.yml
- .pre-commit-config.yaml
- context/test_notebooks.py
- pyproject.toml
- raft-ann-bench/README.md
- raft-ann-bench/cpu/Dockerfile
CI has been failing here for a few weeks, as a result of some failing `cuspatial` notebooks.
As described in https://github.com/rapidsai/cuspatial/issues/1406, I observed those notebooks failing like this:
```text
cannot access local variable 'execution_time' where it is not associated with a value
```
Turns out that that was coming from the `test_notebooks.py` script in this repo. It calls `return execution_time` unconditionally, even though it's possible for that variable to not exist.
This fixes that, and proposes adding a `pre-commit` configuration and corresponding CI job, to help catch such things earlier in the future.
This also proposes skipping some `cuspatial` notebooks, to get CI working. I'd hoped to address that in https://github.com/rapidsai/cuspatial/pull/1407, but most …
> fix return-before-assignment bug in notebook test script, add pre-commit, drop cuspatial notebooks

- .github/workflows/pr.yml
fixes #691
Proposes adding the `pr-builder` workflow, to ensure that all required checks have passed prior to merging (or auto-merging!) here.
This makes auto-merger in this repo behave the way it does across most other repos (https://docs.rapids.ai/resources/auto-merger/).
In exchange, it means all changes will now require a full CI run to be merged. That can take 1-2 hours ([list of recent runs](https://github.com/rapidsai/docker/actions/workflows/pr.yml?query=is%3Asuccess)).
> add pr-builder job

- context/test_notebooks.py
Currently `branch-24.08` is [failing on GHA]( https://github.com/rapidsai/docker/actions/runs/10213535034/job/28292218308#step:9:208 ) because of cuSpatial's `ZipCodes_Stops_PiP_cuSpatial.ipynb`
These failures are already reported in these projects issues:
* https://github.com/rapidsai/cuspatial/issues/1426
To help get 24.08 containers out, skip these notebook in the tests here
> Skip failing notebooks for 24.08

- .github/workflows/build-test-publish-images.yml
- ci/create-multiarch-manifest.sh
- ci/delete-temp-images.sh
**Approach**:
1. Enable the construction of multi-architecture images even if not all image build matrices are successful. This allows for the publishing of manifests for the images that have been successfully built without waiting for all builds to complete.
- In this change, we also modify the multi-arch job to only generate a manifest when the necessary images are available; otherwise, we make the job fail.
2. Modify the deletion job to execute only after the publishing and tests jobs succeed. This prevents the need to restart all jobs when a single image build job fails.
**Here are the new behaviors**:
- The `build-multiarch-manifest` no longer depends on the `build` jobs to all pass before publishing multi-arch images to dockerhub. Once the `build` job completes (either succeeds or …
> enable jobs retry & multi-arch builds of succeeding docker image builds

- raft-ann-bench/cpu/Dockerfile
- raft-ann-bench/gpu/Dockerfile
Reviewing #706, I noticed the following on the Files tab (https://github.com/rapidsai/docker/pull/706/files):
> FromAsCasing: 'as' and 'FROM' keywords' casing do not match
> More info: https://docs.docker.com/go/dockerfile/rule/from-as-casing/
This resolves those warnings. They don't change anything functionally, but I do slightly agree with the style suggestion, and it'd be nice to remove the visual noise of all those warnings in PR reviews.
> resolve warnings about Dockerfile casing

- .github/workflows/build-image.yml
- .github/workflows/build-test-publish-images.yml
- ci/compute-matrix.jq
- ci/create-multiarch-manifest.sh
Accounts for [this condition](https://github.com/rapidsai/docker/blob/branch-24.08/.github/workflows/build-image.yml#L149) for the multiach-manifest job.
> incorporate build condition for raft-cpu-image in multi-arch job

- .github/workflows/build-test-publish-images.yml
- .github/workflows/pr.yml
Follow-up to #702 and #693.
Created based on https://github.com/rapidsai/docker/pull/696#issuecomment-2289689619
`test` jobs are not currently running on pull requests here, because they require `build-multiarch-manifest` jobs, which have this condition that causes such jobs to be skipped on PR builds:
https://github.com/rapidsai/docker/blob/1c27d9245fd9d99ee35981b970acaf10961ca45b/.github/workflows/build-test-publish-images.yml#L171-L172
This PR ensures that `test` jobs always run on PRs, and that merging is blocked until they succeed.
> ensure test jobs always run on PRs

- raft-ann-bench/cpu/Dockerfile
- raft-ann-bench/gpu/Dockerfile
Nightly builds of `rapidsai/raft-ann-bench` failed like this:
> ImportError: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /opt/conda/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-aarch64-linux-gnu.so)
([build link](https://github.com/rapidsai/docker/actions/runs/10739898324/job/29789780257))
I suspect that's because those images use the same pattern for initializing a conda environment that led to the issues described in https://github.com/rapidsai/ci-imgs/issues/185.
This proposes the same fix that we applied in `ci-imgs` (https://github.com/rapidsai/ci-imgs/pull/186).
> raft-ann-bench images: update conda sooner

- dockerhub-readme.md
- matrix-test.yaml
- matrix.yaml
- raft-ann-bench/README.md
- raft-ann-bench/cpu/Dockerfile
- raft-ann-bench/gpu/Dockerfile
Contributes to https://github.com/rapidsai/build-planning/issues/40.
* adds Python 3.12 images
* defaults to latest Python (3.12) and CUDA (12.5[.1]) in docs and comments
Builds here will fail until all RAPIDS libraries are supporting Python 3.12, but figured we don't need to wait on that to come to an agreement about the building and testing matrices.
Blocked by:
> add Python 3.12 images, default to Python 3.12 and CUDA 12.5 in docs

- context/test_notebooks.py
- cuvs-bench/README.md
- dockerhub-readme.md
- matrix-test.yaml
- matrix.yaml
This updates to CUDA 12.8.0.
xref: https://github.com/rapidsai/build-planning/issues/139
> Update to CUDA 12.8.0

- context/entrypoint.sh
- context/test_notebooks.py
Working with @taureandyernv yesterday, we tried something like this to patch in a dependency at run time.
```shell
cat > ./environment.yml <<EOF
channels:
- dglteam/label/th23_cu121
dependencies:
- dgl
EOF
docker run \
--rm \
-v $(pwd)/environment.yml:/home/rapids/environment.yml \
-it rapidsai/base:25.02a-cuda12.5-py3.12 \
conda env export
```
Found that that prompts for confirmation:
```text
Package           Version  Build    Channel                       Size
──────────────────────────────────────────────────────────────────────────
Install:
──────────────────────────────────────────────────────────────────────────
+ dgl    2.4.0.th23.cu121  py312_0  dglteam/label/th23_cu121     295MB
Summary:
Install: 1 packages
Total download: 295MB …
```
> avoid interactive prompts when updating from an environment.yaml

- context/entrypoint.sh
- context/test_notebooks.py
- cuvs-bench/README.md
- dockerhub-readme.md
- matrix-test.yaml
- matrix.yaml
Merge `branch-25.02` into` branch-25.04`, resolves #730
Do NOT squash merge!
> Resolve forward merge conflicts

- context/entrypoint.sh
25.02 ARM containers on CUDA 12.8 are running into an issue of a get_mempolicy call that requires elevated privileges. This very likely will not be desirable for many users, so this change sets the environment NCCL_CUMEM_HOST_ENABLE=0 inside the container that removes the call and makes the containers work similar to prior versions.
This bug only affects RAPIDS libraries that use RAFT comms with NCCL, not NCCL standalone tests, so we are still investigating the root cause. This fix does not seem to have any ill effects during testing and benchmarking though, so it's the fastest way to restore behavior in ARM 12.8 behaviors without needing user intervention.
> Set NCCL_CUMEM_HOST_ENABLE=0 for ARM with CUDA 12.8

- matrix-test.yaml
- matrix.yaml
This migrates amd64 CI jobs to use L4 GPUs from the NVKS cluster.
xref: https://github.com/rapidsai/build-infra/issues/184
> Migrate to NVKS for amd64 CI runners

- .github/workflows/build-cuvs-image.yml
- .github/workflows/build-rapids-image.yml
- .github/workflows/build-test-publish-images.yml
- .github/workflows/pr.yml
- .github/workflows/publish.yml
- .github/workflows/release-to-ngc.yml
- .github/workflows/test-notebooks.yml
- .github/workflows/trigger-breaking-change-alert.yaml
- .pre-commit-config.yaml
- Dockerfile
- ci/common.sh
- ci/compute-matrix.jq
- ci/compute-matrix.sh
- ci/create-cuvs-multiarch-manifest.sh
- ci/create-rapids-multiarch-manifest.sh
- ci/release/update-version.sh
- context/entrypoint.sh
- context/notebooks.sh
- context/test_notebooks.py
- cuvs-bench/cpu/Dockerfile
- cuvs-bench/gpu/Dockerfile
- pyproject.toml
Contributes to #667
Expands testing to improve release confidence in these images.
* adds new `pre-commit` hooks:
- `rapidsai/verify-copyright` = keep copyright notices up to date
- `shellcheck` = catch issues and enforce consistency in shell scripts
* updates all other `pre-commit` hooks
* switches from a manual `run:` to `pre-commit/action@v3.0.1` in CI, for faster runs of `pre-commit` and simpler CI configuration
> add shellcheck, update pre-commit hooks

- context/test_notebooks.py
Fixes #741
Remove ANSI escape sequences like `\x1b[0;31m` from tracebacks printed when reporting notebook failures, to reduce the effort required to investigate those issues. See #741 for more details.
Luckily (😅) I opened this at at time when we had ongoing notebook failures, so could see a traceback. Looks pretty good to me!
([build link](https://github.com/rapidsai/docker/actions/runs/14575734472/job/40882194854?pr=748))
<details><summary>text of logs (click me)</summary>
```text
Testing cuml/forest_inference_demo.ipynb
TypeError ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], line 1
----> 1 fil_model = ForestInference.load(
2     filename=model_path,
3 …
```
> remove ANSI escape sequences in notebook tracebacks

- .github/workflows/build-test-publish-images.yml
- .hadolint.yaml
- .pre-commit-config.yaml
- Dockerfile
- ci/lint-dockerfiles.sh
- cuvs-bench/cpu/Dockerfile
- cuvs-bench/gpu/Dockerfile
Contributes to #667
Proposes running `hadolint` (https://github.com/hadolint/hadolint) on Dockerfiles in this repo. I've found that this tool makes some of the same recommendations that I find myself making in PR reviews... I hope enforcing it in CI will reduce reviewing effort a bit and improve our release confidence.
All the Dockerfiles contain changes for these reported issues, which I agree with:
```text
DL3015 info: Avoid additional packages by specifying `--no-install-recommends`
DL3047 info: Avoid use of wget without progress bar. Use `wget --progress=dot:giga <url>`. Or consider using `-q` or `-nv` (shorthands for `--quiet` or `--no-verbose`).
```
See other comments inline.
As @KyleFromNVIDIA pointed out to me a while ago, the install hooks for `hadolint`'s `pre-commit` hook are …
> lint Dockerfiles with 'hadolint'

- Dockerfile
- tests/container-canary/base.yml
Some users utilize curl across many images to perform healthchecks. In `25.04`, the `cuspatial` notebooks were dropped which also dropped the image's dependency on `curl`.
So this PR explicitly installs the `curl` system package. And just to simplify things, switches to use `curl` to download instead of `wget`.
> Install curl

- .github/copy-pr-bot.yaml
- .github/ops-bot.yaml
- .github/workflows/release-to-nvstaging.yml
- context/cuvs-bench/get_datasets.sh
- context/cuvs-bench/run_benchmark.sh
- context/cuvs-bench/run_benchmarks_preloaded_datasets.sh
- matrix-test.yaml
- matrix.yaml
Modifies the previous `publish-to-ngc` workflow to publish to nvstaging instead.
A [second PR](https://github.com/rapidsai/release-scripts/pull/27) has been opened to add changes to copy the images published by this workflow to NGC public catalog.
> Publish to ngc nvstaging

- .pre-commit-config.yaml
- Dockerfile
- tests/container-canary/base.yml
Fixes https://github.com/rapidsai/ops/issues/4001 (private issue, sorry).
Closes #757
Adds `git` and `wget` to the images. Per @taureandyernv , those tools are so often used in workflows involving these images that it's worth the small additional image size for the convenience of having them pre-installed.
Changes:
* adds `git` and `wget` to the `rapidsai/base` and `rapidsai/notebooks` images
* adds `container-canary` tests to ensure they aren't accidentally removed in the future
* pulls in changes from `pre-commit autoupdate`, to avoid a separate CI run for #757 (since we're making changes here anyway, figured we might as well combine these small updates)
> add git and wget to images

- .github/workflows/build-cuvs-image.yml
- .github/workflows/build-rapids-image.yml
- context/condarc
Contributes to https://github.com/rapidsai/build-planning/issues/166
> Remove dask, pytorch, and nvidia channels

- .github/workflows/build-cuvs-image.yml
- .github/workflows/build-rapids-image.yml
- .pre-commit-config.yaml
Replaces #770
Proposes 2 small changes to help with development here:
* using the DockerHub pull-through cache on NVIDIA's self-hosted runners
- *to reduce the disruption from network issues and rate limits (see https://github.com/rapidsai/ci-imgs/pull/281#issuecomment-3001418760)*
* switching the `pre-commit.ci` autoupdates from weekly to monthly
- *this project uses some tools like `ruff` that update very frequently, meaning we get a new PR from `pre-commit.ci` almost every week... CI here uses a LOT of runners, and for this repo I don't think that resource usage is worth it in exchange for moving to a new version of `ruff` a few weeks earlier than we otherwise would*
> use docker cache, run pre-commit updates less frequently

- context/notebooks.sh
- cuvs-bench/README.md
- dockerhub-readme.md
- matrix-test.yaml
- matrix.yaml
- tests/container-canary/README.md
Contributes to https://github.com/rapidsai/build-planning/issues/208
* uses CUDA 13.0.0 to build and test
> Build and test with CUDA 13.0.0

- context/notebooks.sh
Closes #784 
In #782, we skipped cuML notebook testing on CUDA 13 because there weren't yet CUDA 13 `xgboost` conda packages. Those exist now:
* https://github.com/rapidsai/xgboost-feedstock/issues/100
* https://github.com/rapidsai/integration/pull/800
This reverts a workaround from #782, so all notebooks will be tested on CUDA 12 and CUDA 13. It also ensures that the CUDA 13 images include GPU-accelerated builds of `xgboost`.
> include XGBoost CUDA packages in CUDA 13 images
